<?xml version="1.0" encoding="utf-8"?><Database Name="Concesionario" Class="ConcesionarioDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LOCALHOST;Initial Catalog=Concesionario;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ConcesionarioConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Coche" Member="Coches">
    <Type Name="Coche">
      <Column Name="Id_Coche" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Marca" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Modelo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Motor" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>